/**
 * This file is automatically generated from HTML meta tags.
 * Last updated: 2025-07-09T01:22:15.927Z
 * 
 * DO NOT EDIT MANUALLY - Changes will be overwritten!
 * To update entries, modify the meta tags in your HTML files.
 */

const entries = [
  {
    "title": "．ｑｕａｓｉｍｏｎｏ．",
    "filename": "quasimono.html",
    "description": "＊。．。．。．＊　．ｃｒｅａｔｅ．📝。　ａｓｃｉｉ。　．　ｅｍｏｊｉ．✨。　　　ａｒｔ。🖼．ｆｏｒ　　　．✨。ｓｏｃｉａｌ。　．　ｍｅｄｉａ．🕊＊。．。．。．＊",
    "author": "Jonah J. H.",
    "github": "jonahjoshua",
    "compatibleBrowsers": [
      "Safari Mobile",
      "Chrome Mobile",
      "Safari Desktop",
      "Chrome Desktop",
      "Edge Chromium Desktop",
      "Firefox (probably)"
    ]
  },
  {
    "title": "2D Shooting Game",
    "filename": "botblitz.html",
    "description": "A never ending war against bot's A Fast-paced robot battles await youc change mode play fast or or slow make a high score and challenge your friends to if they beat you no problem tell them you made the high score in hard mode or just beat them again(Currently only works in desktop)",
    "author": "JDot",
    "github": "JDot555"
  },
  {
    "title": "A ring shaped loader with only CSS | one-html-page-challenge",
    "filename": "ring-loader.html",
    "description": "CSS only loaders is still the buzz now so I imported one of my tests.",
    "author": "Markus Mafz",
    "github": "headquarter8302"
  },
  {
    "title": "A S C I I C A M",
    "filename": "ascii-cam.html",
    "description": "Display camera output in colourised ASCII",
    "author": "iveseenthedark",
    "github": "iveseenthedark"
  },
  {
    "title": "A tribute page",
    "filename": "A-tribute-page.html",
    "description": "Just a tribute page to a completely random person",
    "author": "MAZ12211",
    "github": "MAZ12211"
  },
  {
    "title": "Adjustable Fireworks",
    "filename": "adjustable-fireworks.html",
    "description": "A firework generating website with tons of settings.",
    "author": "Tyler Gordon Hill",
    "github": "TyHil"
  },
  {
    "title": "Amsterdam: avoid the bikes & return home!",
    "filename": "avoid-the-bikes.html",
    "description": "You just got your new job in Amsterdam and moved in. After you picked up your new laptop from the Frontmen offices you need to return to your new home. Little did you know about these crazy bikes...",
    "author": "Ioannis Smyrnios - Frontmen",
    "github": "giannissmirnios",
    "compatibleBrowsers": [
      "Chrome Desktop",
      "Firefox Desktop",
      "Safari Desktop",
      "Edge Chromium Desktop"
    ]
  },
  {
    "title": "Animated Fool's Mate",
    "filename": "fools-mate.html",
    "description": "Fool's Mate implemented with CSS Grid and animated grid rows and grid columns.",
    "author": "Chen Hui Jing",
    "github": "huijing",
    "compatibleBrowsers": [
      "Firefox 66+"
    ]
  },
  {
    "title": "Ant Colony",
    "filename": "ant_colony.html",
    "description": "Simulation of an ant colony creating a never ending underground colony. The 'Q' represents a queen that can giver birth to ants 'A'. Food sources are represented by the numbers 9 - 1. (Currently only works in desktop Chrome)",
    "author": "Christopher Powroznik (Metroxe)",
    "github": "Metroxe",
    "compatibleBrowsers": [
      "Chrome Desktop"
    ]
  },
  {
    "title": "Baby Wants Milk",
    "filename": "BabyWantsMilk.html",
    "description": "Baby is home alone and hungry. Take baby 👶 to the milk 🍼. It is my baby step towards HTML/JS/CSS 😉",
    "author": "Seshu Thanneeru",
    "github": "SeshuTechie"
  },
  {
    "title": "Backgroundlights",
    "filename": "backgroundlight.html",
    "description": "Its a hover website, when u hover on a box it will react diiferently and background will keep on changing its color.",
    "author": "rahil",
    "github": "Rahilcode"
  },
  {
    "title": "Base64 to TXT Converter",
    "filename": "Base64toTXT.html",
    "description": "Convert any file to Base64 and download as TXT file",
    "author": "Rupesh Soni",
    "github": "rsoni124"
  },
  {
    "title": "Birthday Cake",
    "filename": "birthday-cake.html",
    "description": "This is a simple animated birthday cake written in Vanilla JavaScript, CSS and HTML. It allows you to set:\n- the number of candles (via param ?candles=15);\n- the addressee name to display the phrase \"Happy Birthday\" with this name (via param ?name=Green);\n- or set your own congratulations (via param ?message=Happy%20Birthday,%20Green&message=Have%20a%20nice%20Day).",
    "author": "Alexander A. Kropotin (ololx)",
    "github": "ololx"
  },
  {
    "title": "bits rain",
    "filename": "bits-rain.html",
    "description": "It's raining bits.",
    "author": "Alexandre Nicolas (Kornflexx)",
    "github": "Kornflexx"
  },
  {
    "title": "Blur loading page",
    "filename": "blur-loading-page.html",
    "description": "A smooth Css transition to slowly load the contents of the web page",
    "author": "Nirban Chakraborty",
    "github": "nirban256"
  },
  {
    "title": "BMI Calculator",
    "filename": "BMI-Calculator.html",
    "description": "A simple BMI calculator",
    "author": "AlexiusOL",
    "github": "AlexiusOL"
  },
  {
    "title": "Box Over It | By Abhay557",
    "filename": "blockoverit.html",
    "description": "A Awesome Game Using-Javascript For One Page Html Challenge",
    "author": "Abhay Mourya (Abhay557)",
    "github": "Abhay557"
  },
  {
    "title": "Bronchalia: The Windy City",
    "filename": "bronchalia.htm",
    "description": "Battle pathogens as the human immune system.",
    "author": "quicksilv3rflash (instructables, reddit)",
    "github": "quicksilv3rflash"
  },
  {
    "title": "Building Price Estimate",
    "filename": "building.html",
    "description": "Drag the top right corner on the building. Price increases as building gets bigger.",
    "author": "Richard Hung (Richard1320)",
    "github": "richard1320"
  },
  {
    "title": "Button Hover",
    "filename": "button-hover.html",
    "description": "a simple button hover",
    "author": "Vanshika Rana",
    "github": "Vanshika-Rana"
  },
  {
    "title": "c o l o r c l o c k",
    "filename": "colorclock.html",
    "description": "Shows you the time with a lovely background generated from the current time.",
    "author": "mechamech",
    "github": "mechamech"
  },
  {
    "title": "Calculator Made By @Abhay557",
    "filename": "Calculator.html",
    "description": "Calculator Using-Javascript For One Page Html Challenge",
    "author": "Abhay Mourya (Abhay557)",
    "github": "Abhay557"
  },
  {
    "title": "Calendar",
    "filename": "calendar.html",
    "description": "A venture into the intricacies of date management in the web\n        browser.",
    "author": "Vincent Lejtzén",
    "github": "lejtzen"
  },
  {
    "title": "Car Game",
    "filename": "mini_car_game.html",
    "description": "simple car racing game, collecting energys on road, speeds up as many energy consumed, slow down if miss energy on road. driving is unlimited",
    "author": "irakli kvirikashvili",
    "github": "zghnachvi"
  },
  {
    "title": "Christopher Powroznik's Movie List",
    "filename": "movie-list.html",
    "description": "Ratings for movies i've seen.",
    "author": "Christopher Powroznik (Metroxe)",
    "github": "Metroxe"
  },
  {
    "title": "Click Game",
    "filename": "aim-click-challenge.html",
    "description": "You basically click the square as many times as you can in 30 seconds",
    "author": "Abdullah Arafat",
    "github": "dolosarafat"
  },
  {
    "title": "Clock",
    "filename": "clock.html",
    "description": "This is an analog-cum-digital clock with both dark and light modes!!",
    "author": "Sumandeep Kaur",
    "github": "Sumandeep-Kaur"
  },
  {
    "title": "Color Quiz",
    "filename": "color-quiz.html",
    "description": "A little quiz about the named colors. You try and guess what the color displayed is called.",
    "author": "Andrea Kaminski (Kazeheki)",
    "github": "kazeheki"
  },
  {
    "title": "Corona Party!",
    "filename": "corona-party.html",
    "description": "Corona Party Hunting Game",
    "author": "Justus Romijn",
    "github": "justusromijn",
    "compatibleBrowsers": [
      "Chrome Desktop",
      "Edge Chromium Desktop",
      "Firefox"
    ]
  },
  {
    "title": "Css Calculator by Aryan Kapoor",
    "filename": "css-calc.html",
    "description": "a css calculator",
    "author": "Aryan Kapoor",
    "github": "Aryankpoor"
  },
  {
    "title": "Dancing Man",
    "filename": "dancing_man.html",
    "description": "The first submission to the One HTML Page Challenge. It is a simple ASCII man starting the dance from Napoleon Dynamite.",
    "author": "Christopher Powroznik (Metroxe)",
    "github": "Metroxe"
  },
  {
    "title": "Date Me Form",
    "filename": "date_me_form.html",
    "description": "Well, this is an application form for asking me on a date kind of thing",
    "author": "Lailah Grant",
    "github": "lailahgrant"
  },
  {
    "title": "Document",
    "filename": "color-change-on-hover-objects.html",
    "description": "Moon and stars showing a twinkiling effect. The background also turns to night view upon hovering over the moon, stars or the body.",
    "author": "Yousuf Uyghur",
    "github": "alfen-yu"
  },
  {
    "title": "Document",
    "filename": "cupWaterWave.html",
    "description": "A cup filled with water and creating wave",
    "author": "Satyabrata Sahoo",
    "github": "satyasonu"
  },
  {
    "title": "Document",
    "filename": "hilbert-curve.html",
    "description": "Draws a hilbert curve, a curve to map a two dimensional space in one dimension",
    "author": "Ahmad Raza",
    "github": "razaahmad333"
  },
  {
    "title": "Documentation Page",
    "filename": "Technical-Doc.html",
    "description": "The basic javascript documentation/cheatsheet",
    "author": "Gorakshnath Bhongal",
    "github": "gbb26"
  },
  {
    "title": "Draw RGB",
    "filename": "draw-rgb.html",
    "description": "A svg draw with RGB.",
    "author": "Erik Giovani",
    "github": "ErikGIovani"
  },
  {
    "title": "FallGame",
    "filename": "fall_game.html",
    "description": "A fall game created using html,css,javascript",
    "author": "Snehal",
    "github": "SNEHAL311998"
  },
  {
    "title": "Fireworks",
    "filename": "fireworks.html",
    "description": "Clickable fireworks!",
    "author": "Matthew Hu",
    "github": "wagabooga"
  },
  {
    "title": "FISHIES",
    "filename": "fishies.html",
    "description": "Fishies swimming",
    "author": "William Chung",
    "github": "wiiliam"
  },
  {
    "title": "Fortune Cookie Generator",
    "filename": "fortune-cookie-generator.html",
    "description": "Prints a fortune cookie message on the screen, randomly generated by an algorithm.",
    "author": "Hector Krionas Lamprou",
    "github": "EKrionasLamprou"
  },
  {
    "title": "game of life",
    "filename": "game_of_life.html",
    "description": "A simple implementation of Conway's Game of Life in JS.",
    "author": "bendersteed",
    "github": "bendersteed"
  },
  {
    "title": "GO Game",
    "filename": "go.html",
    "description": "Play to go game",
    "author": "Geun Lim",
    "github": "shing100"
  },
  {
    "title": "Graphing Tool",
    "filename": "mandelbrot.html",
    "description": "Simple mandelbrot fractal viewer in WebGL. Zoom in and move around with the mouse.",
    "author": "Parkin Pham",
    "github": "P4GAN"
  },
  {
    "title": "Guess My Number!",
    "filename": "guess_my_number.html",
    "description": "You have to guess the number genarated by the system",
    "author": "Soumojit Chakraborty",
    "github": "SOUMOJIT-CHAKRABORTY"
  },
  {
    "title": "Guess the Number",
    "filename": "openai-generated-entry.html",
    "description": "This entry was coded completely by OpenAI using the prompt \"code me a game in one html file\".",
    "author": "OpenAI",
    "github": "openai"
  },
  {
    "title": "Hangman",
    "filename": "hangman.html",
    "description": "Hangman game",
    "author": "Sandro Roth",
    "github": "rothsandro"
  },
  {
    "title": "Image To Base64 Converter | PiXELCONVERTOR",
    "filename": "PiXELCONVERTOR.html",
    "description": "Convert image to base64 online. Support JPG, PNG, GIF, Webp, BMP.",
    "author": "Rupesh Soni",
    "github": "rsoni124"
  },
  {
    "title": "Interactive Resume Builder",
    "filename": "interactiveResumeBuilder.html"
  },
  {
    "title": "Interval",
    "filename": "Interval.html",
    "description": "Increase reading speed by training in short bursts.",
    "author": "John Gillespie",
    "github": "olddognewtrix123"
  },
  {
    "title": "JUST HTML!",
    "filename": "just_html.html",
    "description": "Nothing to see here. This was an HTML challenge, so I tried to do just HTML.",
    "author": "Shawn Oden",
    "github": "shawnoden"
  },
  {
    "title": "KNFL",
    "filename": "knfl.html",
    "description": "A one-throw-kniffel-like game.",
    "author": "Pascal Claisse",
    "github": "pclaisse"
  },
  {
    "title": "Ladner British Columbia",
    "filename": "ladner_british_columbia.html",
    "description": "Applied an <feTurbulence> to an image of my hometown Ladner British Columbia, in order to create a cool water effect.",
    "author": "Christopher Powroznik (Metroxe)",
    "github": "Metroxe"
  },
  {
    "title": "Large 2D Maze Game",
    "filename": "maze.html",
    "description": "A 64x64 maze game where you have to finish in order to get confetti. W A S D.",
    "author": "Alex Manochio",
    "github": "ajm19826"
  },
  {
    "title": "Magic Wand",
    "filename": "magicWand.html",
    "description": "Wave your magic wand!  A simple demo using mouse motion and button.",
    "author": "Jacob Ewing",
    "github": "jacobEwing"
  },
  {
    "title": "Marching Squares",
    "filename": "marching-squares.html",
    "description": "Marching Squares algorithm in one HTML page!",
    "author": "Magoninho",
    "github": "Magoninho"
  },
  {
    "title": "Meat on the Move",
    "filename": "meat-on-the-move.html",
    "description": "It's meat on the move!",
    "author": "Jeff Phillips"
  },
  {
    "title": "Memory Game",
    "filename": "memory-game.html",
    "description": "Simple memory testing game that I created during a flight while my laptop battery slowly approached 0%. Each level gets faster & adds 1 more color in randomized order to remember!",
    "author": "Spencer Gray",
    "github": "spencergray96"
  },
  {
    "title": "My Contacts",
    "filename": "contact_list.html",
    "description": "Contact List where contacts saved at local storage",
    "author": "Rahul Reddy",
    "github": "rahulreddy-001"
  },
  {
    "title": "New year counter",
    "filename": "simple-counter.html",
    "description": "This is a simple counter for 2023 new year with gradient color background!!",
    "author": "Israa Gargar",
    "github": "Esogargar"
  },
  {
    "title": "One Html Page Challenge",
    "filename": "pink-vs-unknowns.html",
    "description": "Pink vs Unknowns is a simulation where two sides have opposite contradictory missions.",
    "author": "Aliaksandr B.",
    "github": "ByAliaksandr",
    "compatibleBrowsers": [
      "Chrome Desktop",
      "Firefox Desktop",
      "Safari Desktop"
    ]
  },
  {
    "title": "Out On A Limb",
    "filename": "out_on_a_limb.html",
    "description": "Aesthetic lyric page for Out on a limb by Jayaire Woods.",
    "author": "Christopher Powroznik (Metroxe)",
    "github": "Metroxe"
  },
  {
    "title": "Photorealism CSS Still Life",
    "filename": "pure-css-still-life-water-lemon.html",
    "description": "A Pure CSS Still Life. No images, No SVG, just CSS, absolutely pointless!",
    "author": "Ben Evans",
    "github": "ivorjetski"
  },
  {
    "title": "Ping Pong",
    "filename": "ping-pong.html",
    "description": "Ping Pong is a classical arcade game which you can play with two people. You can also set the computer as an auto player, moreover set two auto players and watch them while they play against each other.",
    "author": "Osman Fikret Ceylan",
    "github": "ofcyln",
    "compatibleBrowsers": [
      "Chrome Desktop",
      "Firefox Desktop",
      "Safari Desktop",
      "Edge Chromium Desktop",
      "Brave Desktop"
    ]
  },
  {
    "title": "Platform",
    "filename": "platform.html",
    "description": "v3.0 - Just a simple JavaScript game",
    "author": "Platform",
    "github": "Mini-Ware"
  },
  {
    "title": "Prim's Maze",
    "filename": "PrimsMaze.html",
    "description": "A maze randomly generated using Prim's Algorithm.",
    "author": "Inparsian",
    "github": "inparsian"
  },
  {
    "title": "Puzzle",
    "filename": "tiles.html",
    "description": "Tile ordering game.",
    "author": "Marc Lajoie",
    "github": "quickhand"
  },
  {
    "title": "Random Color Generator",
    "filename": "color-grid.html",
    "description": "Renders cards of random colors that can be copied by clicking on the card. Reload button to generate new cards.",
    "author": "Rishabh Singh",
    "github": "Rishabh-Singh-Codes"
  },
  {
    "title": "Random colour generator",
    "filename": "RandomColourGenerator.html",
    "description": "A random colour generator which shows you different colours after every click",
    "author": "Rajiv Sahal",
    "github": "Ryukemeister"
  },
  {
    "title": "Random Password",
    "filename": "randomPassword.html",
    "description": "Generate random strong passwords",
    "author": "Ankita",
    "github": "AnkitaMalik22"
  },
  {
    "title": "Registration form",
    "filename": "Sattyam.html",
    "description": "Created a Static student Registration Form",
    "author": "Sattyam Samania",
    "github": "SattyamSamania"
  },
  {
    "title": "Rip Moose",
    "filename": "Sidhumoosewala-tribute-page.html",
    "description": "A small tribute to a legend",
    "author": "Guneet Singh",
    "github": "IamGuneet"
  },
  {
    "title": "Ripples",
    "filename": "ripples.html",
    "description": "Pleasant rippling circles appearing on the page",
    "author": "Nicola Cerutti",
    "github": "ncerutti"
  },
  {
    "title": "Shape Dodge Frenzy",
    "filename": "shape-dodge-frenzy.html",
    "description": "A cool and simple game where you(a shape) try to dodge other falling shapes.",
    "author": "Abhi (d2crashout)",
    "github": "d2crashout"
  },
  {
    "title": "signup html",
    "filename": "signup_page.html",
    "description": "Simple signup page with no css by nithish gajula",
    "author": "Nithish Gajula",
    "github": "nithish-gajula"
  },
  {
    "title": "Simon Game",
    "filename": "simon-game.html",
    "description": "Well known simon game, short term memory game",
    "author": "Sai Mahith Reddy Bekkem",
    "github": "mahith257"
  },
  {
    "title": "Snakegame",
    "filename": "Snakegame.html",
    "description": "My first submission to the One HTML Page Challenge.It is a simple snake game using html, css and javascript.",
    "author": "Kuljeet Singh (Kuljeet-123)",
    "github": "Kuljeet-123"
  },
  {
    "title": "StopWatch",
    "filename": "stopWatch.html",
    "description": "An online stopwatch to keep your performance in check",
    "author": "Kabir Seth",
    "github": "sethkabir"
  },
  {
    "title": "Strange Insults",
    "filename": "strange_insults.html",
    "description": "An insult generator.",
    "author": "Christopher Powroznik (Metroxe)",
    "github": "Metroxe"
  },
  {
    "title": "Task List",
    "filename": "taskListApp.html",
    "description": "A task list application with local storage and filter tasks functionality",
    "author": "Tejashwa Rajvardhan",
    "github": "tejash023"
  },
  {
    "title": "Tic-Tac-Toe Game",
    "filename": "tic-tac-toe.html",
    "description": "It is just a simple tic tac toe game!",
    "author": "Sumandeep Kaur",
    "github": "Sumandeep-Kaur"
  },
  {
    "title": "Time Sheet Calculator",
    "filename": "calculate_hours_worked.html",
    "description": "Calculates the amount of hours worked based on the start and end time of the work shifts and break times if there is any.",
    "author": "Jacky Ly",
    "github": "lyjacky11"
  },
  {
    "title": "Tip-Calculator",
    "filename": "Tips-Calculator.html",
    "description": "A simple Tips-calculator",
    "author": "Amaan Haider",
    "github": "AmaanHaider"
  },
  {
    "title": "Todo list",
    "filename": "todo_list.html",
    "description": "Just another one todo list.",
    "author": "Rafał Goławski",
    "github": "rago4"
  },
  {
    "title": "Ultimate Sudoku",
    "filename": "UdhavSudoku.html",
    "description": "A Basic Sudoku Game which solves sudoku puzzle if places filled correctly.",
    "author": "Udhav Sharma",
    "github": "UdhavSharma2004"
  },
  {
    "title": "Wargames",
    "filename": "wargames.html",
    "description": "Recreation of the terminal window from a scene in the movie Wargames.",
    "author": "Vasilios Daskalopoulos",
    "github": "vasil9v"
  },
  {
    "title": "WaterMelon !",
    "filename": "watermelon-pixel.html",
    "description": "A Simple Oui.",
    "author": "Maxime DO",
    "github": "Maxime-DO"
  },
  {
    "title": "Web Minesweeper",
    "filename": "webmine.html",
    "description": "Nearly full implementation of the original Minesweeper game (no high scores list).  Left click to hit a square and test for mines, right click to plant a flag.",
    "author": "Terry McKay",
    "github": "terrymckay"
  },
  {
    "title": "Whack-A-Mole",
    "filename": "whack-a-mole.html",
    "description": "New whack-a-mole with speed rounds and shufffle keyboard",
    "author": "sakshi",
    "github": "sakshi-011"
  },
  {
    "title": "What is my Screen Resolution",
    "filename": "my-screen-resolution.html",
    "description": "THIS PAGE HELPS YOU TO FIND YOUR MONITOR/SCREEN RESOLUTIONS.",
    "author": "Prateek Singh",
    "github": "7ORP3DO",
    "compatibleBrowsers": [
      "Chrome",
      "Edge",
      "Firefox",
      "Internet Explorer",
      "Opera",
      "Safari"
    ]
  },
  {
    "title": "You're in Debt.",
    "filename": "organs-for-debt.html",
    "description": "You have a lot of debt and nothing but your body to pay for it",
    "author": "Justin Chao",
    "github": "jutsK"
  },
  {
    "title": "Your IP",
    "filename": "ip.html",
    "description": "Find out what's your IP address",
    "author": "Elisha Hollander (donno2048)",
    "github": "donno2048"
  }
];